
server:
  port: 8762


#Application name
spring:
  application:
    name: micro-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localost:8761/eureka/,http://localhost:8862/eureka/